// SPDX-License-Identifier: MIT
//
// pto-peaks: the Poisson survival function and its SIMD log-gamma core.
//
// This is the module's numerical contract. Everything downstream of it -- the
// Benjamini-Hochberg pass, the summit scores, the narrowPeak q-value column --
// is a monotone transform of what `log_poisson_sf` returns, so an error here
// does not produce a visibly broken peak call. It produces a plausible one.
// That is the reason this suite is as large as it is.
//
// Four kinds of check, and the distinction matters when one of them fails:
//
//   1. GOLDEN VALUES.  ln P(X >= k) at 80 significant digits from mpmath's
//      regularised incomplete gamma -- a different algorithm, a different
//      arithmetic, and not derived from this header. Generated by
//      scripts/gen_poisson_golden.py; see that file to add cases.
//   2. CLOSED FORMS.  P(X >= 1) = 1 - e^-lam and P(X >= 2) = 1 - e^-lam(1+lam)
//      are exact algebra, so they pin small k independently of any table.
//   3. STRUCTURAL PROPERTIES.  Monotone in k, monotone in lam, always finite,
//      never positive, fail-closed on a degenerate lambda. These hold for
//      every input, including the ones no golden table would think to list.
//   4. SIMD/SCALAR PARITY.  Every kernel compiled into this binary, driven
//      explicitly through `*_batch_isa` rather than through whatever the host
//      CPU happens to dispatch to -- one machine exercises every path.
//
// The tolerances are derived, not tuned. `poisson_tolerance()` carries the
// error model and the reason it differs between the two branches; read it
// before loosening anything.
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <limits>
#include <random>
#include <regex>
#include <string>
#include <vector>

#include "peaks/poisson_model.hpp"

namespace {

using pto::peaks::IsaLevel;

long long g_failures = 0;
long long g_checks = 0;

void report(bool ok, const char* expr, int line, const std::string& detail = {}) {
  ++g_checks;
  if (ok) return;
  ++g_failures;
  std::fprintf(stderr, "  FAIL %s:%d: %s%s%s\n", __FILE__, line, expr,
               detail.empty() ? "" : " -- ", detail.c_str());
}

std::string num(double v) {
  char buf[40];
  std::snprintf(buf, sizeof(buf), "%.17g", v);
  return buf;
}

#define CHECK(expr) report((expr), #expr, __LINE__)
#define CHECK_MSG(expr, detail) report((expr), #expr, __LINE__, (detail))

// |a - b| <= tol, reported with both values so a failure is diagnosable
// without a debugger.
void check_near(double a, double b, double tol, const char* expr, int line) {
  const bool ok = std::isfinite(a) && std::isfinite(b) && std::fabs(a - b) <= tol;
  report(ok, expr, line,
         num(a) + " vs " + num(b) + " (delta " + num(std::fabs(a - b)) +
             ", tol " + num(tol) + ")");
}

#define CHECK_NEAR(a, b, tol) check_near((a), (b), (tol), #a " ~= " #b, __LINE__)

#define CHECK_REL(a, b, rel)                                                  \
  check_near((a), (b), std::fabs(static_cast<double>(b)) * (rel) +            \
                           std::numeric_limits<double>::min(),                \
             #a " ~= " #b " (rel)", __LINE__)

constexpr double kEps = std::numeric_limits<double>::epsilon();
constexpr double kInf = std::numeric_limits<double>::infinity();
const double kNaN = std::numeric_limits<double>::quiet_NaN();

// ---------------------------------------------------------------------------
// The error model.
//
// log_poisson_sf builds every answer on the leading log-term
//
//     lead = -lam + k*ln(lam) - lnGamma(k)
//
// whose three parts each reach O(k*ln k) and then cancel. The absolute error
// of `lead` is therefore eps times the LARGEST TERM, not eps times the answer
// -- at k = 1e5, lam = 1000 the terms are ~1e6 and the answer is ~-3.6e5, so
// an error of 1e-10 is already the best a double can do.
//
// How that error reaches the result depends on the branch, which is why one
// tolerance for both would be either vacuous or impossible:
//
//   * lam < k+1 (upper tail; the enriched, interesting case) the result is
//     lead + ln(series), so the error is ADDITIVE and bounded by eps*scale.
//   * lam >= k+1 (P near 1) the result is log1p(-Q) with Q = exp(lead)*CF, so
//     an absolute error in `lead` is a RELATIVE error in Q, and hence a
//     relative error in the answer. Demanding absolute agreement there would
//     let a badly wrong -3.7e-42 pass; demanding relative agreement in the
//     other branch would demand more than a double holds.
//
// 64 units of eps is roughly 16x the four roundings actually incurred. It is
// headroom, not a fudge factor: tighten it and it still passes today, but the
// margin is what keeps the suite from failing on a libm difference between two
// CI runners rather than on a real regression.
constexpr double kEpsUnits = 64.0;

double term_scale(std::uint32_t k, double lam) {
  const double a = static_cast<double>(k);
  const double lg = (a >= 1.0) ? std::lgamma(a) : 0.0;
  return std::max(1.0, lam + a * std::fabs(std::log(lam)) + std::fabs(lg));
}

double poisson_tolerance(std::uint32_t k, double lam, double golden) {
  const double s = kEpsUnits * kEps * term_scale(k, lam);
  if (lam < static_cast<double>(k) + 1.0) {
    return s + 8.0 * kEps * std::fabs(golden);  // additive branch
  }
  return std::fabs(golden) * (s + 8.0 * kEps);  // multiplicative branch
}

// ---------------------------------------------------------------------------
// Golden values (mpmath, 80 dps). See the file header.
// ---------------------------------------------------------------------------

struct SfGolden {
  std::uint32_t k;
  double lam;
  double ln_sf;
};

const SfGolden kSfGolden[] = {
    {1u, 1e-300, -690.77552789821370521},
    {1u, 1e-10, -23.02585092999045684},
    {1u, 0.5, -0.93275212956718857189},
    {1u, 1.0, -0.45867514538708189102},
    {1u, 10.0, -0.000045400960370489209504},
    // True value -5.0759588975494567653e-435: below the smallest denormal, so
    // -0.0 is the closest double there is. Written as a zero rather than as a
    // literal the compiler would have to warn about and then flush anyway.
    {1u, 1000.0, -0.0},
    {2u, 0.5, -2.4056813913603713434},
    {2u, 1.0, -1.3308932682040545336},
    {2u, 2.0, -0.52088580766434435568},
    {2u, 3.0, -0.22207945950008767602},
    {2u, 100.0, -3.7572767357810443226e-42},
    {3u, 1.0, -2.5219682600313997855},
    {3u, 3.0, -0.55024249677722107397},
    {3u, 4.0, -0.27194430407872768518},
    {5u, 1.0, -5.6103339828971544038},
    {5u, 5.0, -0.58069974963142130617},
    {5u, 6.0, -0.33555176083234828795},
    {10u, 1.0, -16.009909825202021882},
    {10u, 5.0, -3.4474070729719001203},
    {10u, 9.0, -0.88529665995988917495},
    {10u, 10.0, -0.61235960785375468761},
    {10u, 11.0, -0.41628944412807576349},
    {10u, 20.0, -0.005007931088754225646},
    {50u, 10.0, -43.1313793140824281},
    {50u, 49.0, -0.77196445325035818369},
    {50u, 50.0, -0.6562207983875686789},
    {50u, 51.0, -0.55443821059725629345},
    {50u, 80.0, -0.00013079252956141261489},
    {100u, 1.0, -364.72942620471961936},
    {100u, 50.0, -21.862679706410285814},
    {100u, 99.0, -0.74801669273621219165},
    {100u, 100.0, -0.6668971505852893696},
    {100u, 101.0, -0.59258482952306249928},
    {100u, 200.0, -1.8438936497115758513e-15},
    // The log-factorial table ends at 512; 513 and 514 are the first two
    // answers that come from the Stirling series instead of a load.
    {511u, 100.0, -426.36299527550708873},
    {512u, 100.0, -427.99662196308870118},
    {513u, 100.0, -429.63219781488746899},
    {514u, 100.0, -431.26971904449510964},
    {513u, 512.0, -0.71692979173309915581},
    {513u, 513.0, -0.68147297545207404463},
    {513u, 514.0, -0.6472959403332114772},
    {1000u, 1.0, -5913.1271789888282654},
    {1000u, 100.0, -1406.8527552662533343},
    {1000u, 999.0, -0.71011751341301442634},
    {1000u, 1000.0, -0.68477186329031014615},
    {1000u, 1001.0, -0.66007716551745524796},
    {1000u, 2000.0, -6.84734945961475318e-136},
    {10000u, 9999.0, -0.69848080750297378074},
    {10000u, 10000.0, -0.69049109440197235942},
    {10000u, 10001.0, -0.68256550060953117664},
    {100000u, 1000.0, -361523.68395067433577},
    {100000u, 99999.0, -0.69483069147870253789},
    {100000u, 100001.0, -0.68978866886003341611},
    {1000000u, 999000.0, -1.8410218993793995822},
    {1000000u, 1001000.0, -0.17275373112418319036},
    // Counts past 2^31, where lnGamma(k) is ~1e11 and every term of `lead`
    // has an ulp of 1e-5. Summed from the exact tail series at 80 dps.
    {65536u, 1024.0, -208051.01012019778017},
    {100000u, 50000.0, -19320.700330911594295},
    {1000000u, 1.0, -12815519.384657169625},
    {2147483648u, 1000.0, -29162415170.866269071},
    {4294967295u, 1000000.0, -31634289781.870898019},
    {4294967295u, 1000000000.0, -2964706776.5142036504},
};

struct LgammaGolden {
  double z;
  double lg;
};

const LgammaGolden kLgammaGolden[] = {
    {0.5, 0.57236494292470008707},
    {1.0, 0.0},
    {1.5, -0.12078223763524522235},
    {2.0, 0.0},
    {2.5, 0.28468287047291915963},
    {3.0, 0.69314718055994530942},
    {3.7, 1.4280723266653879219},
    {7.25, 7.0521854507385394449},
    {15.999, 27.896530402760148831},
    {16.0, 27.899271383840891566},
    {16.001, 27.902012429415417749},
    {17.0, 30.671860106080672804},
    {100.5, 361.43554046777762156},
    {512.5, 2682.9410651732424342},
    {1000.5, 5908.6741758486774887},
    {1000000.0, 12815504.56914761166},
    {1000000.5, 12815511.476902765642},
    {1000000000000000.0, 33538776394910668.91},
    {1e+100, 2.292585092994045684e+102},
    {1e+300, 6.8977552789821370521e+302},
};

struct FactorialGolden {
  std::uint32_t k;
  double lf;
};

const FactorialGolden kFactorialGolden[] = {
    {0u, 0.0},
    {1u, 0.0},
    {2u, 0.69314718055994530942},
    {3u, 1.7917594692280550008},
    {10u, 15.104412573075515295},
    {20u, 42.33561646075348503},
    {21u, 45.380138898476908026},
    {170u, 706.57306224578734711},
    {511u, 2679.8221470013088753},
    {512u, 2686.0604716263483831},
    {513u, 2692.3007474715191526},
    {1000u, 5912.1281784881633489},
    {100000u, 1051299.2218991218651},
    {4294967295u, 90970455792.054889932},
};

// ===========================================================================
// 1. The elementary kernels: this module's replacements for libm.
//
// They are tested against libm rather than against a golden table because the
// platform's log/exp ARE the reference for a single elementary function -- the
// point of owning them is vectorisation and the absence of a call, not better
// accuracy than the system.
// ===========================================================================

void test_log_kernel_matches_libm() {
  const double points[] = {
      1.0, 2.0, 0.5, 4.0, 1e-300, 1e300, 3.0, 7.0,
      2.718281828459045, 3.141592653589793,
      0.9999999999999999, 1.0000000000000002, 1.4142135623730951,
      0.7071067811865476, 1e-10, 1e10, 1024.0, 1023.999999,
      std::numeric_limits<double>::min(),        // smallest normal
      std::numeric_limits<double>::denorm_min(), // smallest denormal
      5e-324, 2.2250738585072011e-308,           // denormal boundary
      std::numeric_limits<double>::max(),
  };
  for (double x : points) {
    CHECK_REL(pto::peaks::log_approx(x), std::log(x), 4.0 * kEps);
  }

  std::mt19937_64 rng(20260909);
  std::uniform_real_distribution<double> mant(1.0, 2.0);
  std::uniform_int_distribution<int> expo(-1020, 1020);
  for (int i = 0; i < 20000; ++i) {
    const double x = std::ldexp(mant(rng), expo(rng));
    CHECK_REL(pto::peaks::log_approx(x), std::log(x), 4.0 * kEps);
  }

  // Subnormals are their own path: the mantissa cannot be extracted by the
  // usual bit split without first scaling the value into the normal range.
  for (int i = 1; i < 400; ++i) {
    const double x = std::ldexp(1.0, -1074 + i) * 1.5;
    CHECK_REL(pto::peaks::log_approx(x), std::log(x), 4.0 * kEps);
  }

  // Domain edges, which must agree with libm rather than trap.
  CHECK(pto::peaks::log_approx(0.0) == -kInf);
  CHECK(pto::peaks::log_approx(-0.0) == -kInf);
  CHECK(std::isnan(pto::peaks::log_approx(-1.0)));
  CHECK(std::isnan(pto::peaks::log_approx(kNaN)));
  CHECK(pto::peaks::log_approx(kInf) == kInf);
  CHECK(pto::peaks::log_approx(1.0) == 0.0);
}

void test_exp_kernel_matches_libm() {
  const double points[] = {0.0,   1.0,   -1.0,  0.5,   -0.5,   709.0,  -708.0,
                           -745.0, 700.0, 1e-20, -1e-20, 0.3465735902799726,
                           -0.3465735902799726, 100.0, -100.0, 20.0, -20.0};
  for (double x : points) {
    CHECK_REL(pto::peaks::exp_approx(x), std::exp(x), 4.0 * kEps);
  }

  std::mt19937_64 rng(20260910);
  std::uniform_real_distribution<double> u(-700.0, 700.0);
  for (int i = 0; i < 20000; ++i) {
    const double x = u(rng);
    CHECK_REL(pto::peaks::exp_approx(x), std::exp(x), 4.0 * kEps);
  }

  // Gradual underflow: exp(-745) is denormal and exp(-746) is zero. Getting
  // this wrong the other way -- returning a normal number -- would make an
  // impossible p-value look merely small.
  for (double x = -700.0; x > -760.0; x -= 0.5) {
    CHECK_REL(pto::peaks::exp_approx(x), std::exp(x), 1e-10);
  }
  CHECK(pto::peaks::exp_approx(-800.0) == 0.0);
  CHECK(pto::peaks::exp_approx(-kInf) == 0.0);
  CHECK(pto::peaks::exp_approx(800.0) == kInf);
  CHECK(pto::peaks::exp_approx(kInf) == kInf);
  CHECK(std::isnan(pto::peaks::exp_approx(kNaN)));
  CHECK(pto::peaks::exp_approx(0.0) == 1.0);
}

void test_log1p_kernel_matches_libm() {
  // The whole reason log1p exists here: log(1 + y) for tiny y throws the
  // answer away. A p-value of 1 - 3.8e-42 is not the same number as 1.
  const double points[] = {0.0,   1e-300, -1e-300, 1e-17,  -1e-17, 0.5,
                           -0.5,  1.0,    -0.9,    -0.99,  100.0,  1e300,
                           -0.3333333333333333, 0.4142135623730951,
                           -0.2928932188134524};
  for (double y : points) {
    CHECK_REL(pto::peaks::log1p_approx(y), std::log1p(y), 4.0 * kEps);
  }

  std::mt19937_64 rng(20260911);
  std::uniform_real_distribution<double> u(-0.5, 0.5);
  for (int i = 0; i < 20000; ++i) {
    const double y = u(rng);
    CHECK_REL(pto::peaks::log1p_approx(y), std::log1p(y), 4.0 * kEps);
  }
  for (int i = 0; i < 5000; ++i) {
    const double y = -std::ldexp(u(rng) + 0.5, -(i % 200));  // approach -0 and -1
    CHECK_REL(pto::peaks::log1p_approx(y), std::log1p(y), 8.0 * kEps);
  }

  CHECK(pto::peaks::log1p_approx(-1.0) == -kInf);
  CHECK(std::isnan(pto::peaks::log1p_approx(-2.0)));
  CHECK(std::isnan(pto::peaks::log1p_approx(kNaN)));
  CHECK(pto::peaks::log1p_approx(0.0) == 0.0);
}

// ===========================================================================
// 2. log-gamma
// ===========================================================================

void test_log_factorial_matches_golden() {
  for (const auto& g : kFactorialGolden) {
    CHECK_REL(pto::peaks::log_factorial(g.k), g.lf,
              (g.lf == 0.0) ? 0.0 : 8.0 * kEps);
  }
  // 0! and 1! are 1, and their logarithm is a zero this must produce exactly
  // rather than approximately: a peak caller divides by nothing here, but a
  // -0.0 or a 1e-17 propagates into every downstream sum.
  CHECK(pto::peaks::log_factorial(0) == 0.0);
  CHECK(pto::peaks::log_factorial(1) == 0.0);
}

void test_log_factorial_matches_libm_over_the_table_and_past_it() {
  for (std::uint32_t k = 0; k <= 4000; ++k) {
    const double ref = std::lgamma(static_cast<double>(k) + 1.0);
    CHECK_REL(pto::peaks::log_factorial(k), ref, (ref == 0.0) ? 0.0 : 8.0 * kEps);
  }
  for (std::uint32_t k : {100000u, 1000000u, 16777216u, 2147483647u, 4294967295u}) {
    CHECK_REL(pto::peaks::log_factorial(k), std::lgamma(static_cast<double>(k) + 1.0),
              8.0 * kEps);
  }
}

void test_log_factorial_table_seam_is_continuous() {
  // The table ends at kLogFactorialTableMax and the Stirling series takes over
  // on the next index. A discontinuity there would be invisible in any single
  // value and would show up as a step in the p-value track at one pileup depth.
  const std::uint32_t m = pto::peaks::kLogFactorialTableMax;
  for (std::uint32_t k = m - 3; k <= m + 3; ++k) {
    const double ours = pto::peaks::log_factorial(k);
    const double ref = std::lgamma(static_cast<double>(k) + 1.0);
    CHECK_REL(ours, ref, 8.0 * kEps);
    // ln(k!) - ln((k-1)!) is exactly ln(k), across the seam as anywhere else.
    if (k > 0) {
      const double step = ours - pto::peaks::log_factorial(k - 1);
      CHECK_REL(step, std::log(static_cast<double>(k)), 1e-13);
    }
  }
}

void test_lgamma_matches_golden() {
  for (const auto& g : kLgammaGolden) {
    // lnGamma has zeros at 1 and 2, so relative accuracy is not a meaningful
    // demand in their neighbourhood -- the absolute floor covers it, and the
    // Poisson path never evaluates a non-integer argument anyway.
    check_near(pto::peaks::lgamma_approx(g.z), g.lg,
               std::fabs(g.lg) * 16.0 * kEps + 1e-13, "lgamma_approx golden",
               __LINE__);
  }
  CHECK(pto::peaks::lgamma_approx(1.0) == 0.0);
  CHECK(pto::peaks::lgamma_approx(2.0) == 0.0);
}

void test_lgamma_matches_libm_sweep() {
  std::mt19937_64 rng(20260912);
  std::uniform_real_distribution<double> small(1e-6, 16.0);
  for (int i = 0; i < 20000; ++i) {
    const double z = small(rng);
    check_near(pto::peaks::lgamma_approx(z), std::lgamma(z),
               std::fabs(std::lgamma(z)) * 16.0 * kEps + 1e-13, "lgamma small",
               __LINE__);
  }
  std::uniform_real_distribution<double> big(16.0, 1e8);
  for (int i = 0; i < 20000; ++i) {
    const double z = big(rng);
    CHECK_REL(pto::peaks::lgamma_approx(z), std::lgamma(z), 16.0 * kEps);
  }
}

void test_lgamma_guards_its_domain() {
  // The poles. Returning something finite here is the dangerous direction:
  // `lead` subtracts lnGamma, so a finite wrong value at a pole becomes a
  // finite wrong p-value instead of an obviously absent one.
  CHECK(pto::peaks::lgamma_approx(0.0) == kInf);
  CHECK(pto::peaks::lgamma_approx(-0.0) == kInf);
  CHECK(pto::peaks::lgamma_approx(-1.0) == kInf);
  CHECK(pto::peaks::lgamma_approx(-2.0) == kInf);
  CHECK(pto::peaks::lgamma_approx(-1e300) == kInf);
  // Negative non-integers are outside the supported domain and are reported as
  // absent rather than reflected: nothing in a peak caller has one.
  CHECK(pto::peaks::lgamma_approx(-0.5) == kInf);
  CHECK(std::isnan(pto::peaks::lgamma_approx(kNaN)));
  CHECK(pto::peaks::lgamma_approx(kInf) == kInf);
  // Denormal and tiny arguments: lnGamma(z) ~ -ln(z) as z -> 0.
  CHECK_REL(pto::peaks::lgamma_approx(1e-300), std::lgamma(1e-300), 1e-13);
  CHECK_REL(pto::peaks::lgamma_approx(5e-324), std::lgamma(5e-324), 1e-13);
}

// ===========================================================================
// 3. The Poisson survival function
// ===========================================================================

void test_sf_matches_golden() {
  for (const auto& g : kSfGolden) {
    const double ours = pto::peaks::log_poisson_sf(g.k, g.lam);
    check_near(ours, g.ln_sf, poisson_tolerance(g.k, g.lam, g.ln_sf),
               "log_poisson_sf golden", __LINE__);
  }
}

void test_sf_k_zero_is_exactly_zero() {
  // P(X >= 0) = 1 for every lambda, and ln(1) is 0 exactly. An epsilon here
  // survives -log10 and BH and lands in the output column.
  for (double lam : {1e-300, 1e-10, 0.5, 1.0, 10.0, 1e6, 1e30, 1e300}) {
    CHECK(pto::peaks::log_poisson_sf(0, lam) == 0.0);
    CHECK(pto::peaks::neg_log10_poisson_sf(0, lam) == 0.0);
  }
}

void test_sf_small_k_closed_forms() {
  // P(X >= 1) = 1 - e^-lam and P(X >= 2) = 1 - e^-lam (1 + lam) are exact
  // algebra, so they pin small k independently of any table, any series and
  // any continued fraction.
  //
  // Getting a reference OUT of that algebra in double precision is the harder
  // half, and the first two attempts were both worse than the code under test:
  //
  //   log(-expm1(-lam))       loses the answer entirely once lam is large.
  //                           At lam = 45 the true ln P is -2.86e-20 and this
  //                           returns 0, because 1 - 2.9e-20 is the double 1.
  //   log1p(-exp(-lam))       loses it at the other end: for small lam,
  //                           1 - e^-lam cancels down to a few ulp of 1.
  //
  // Each is sharp on the half where the other fails, which is the branch
  // below. The k = 2 form has no such split -- e^-lam(1+lam) approaches 1 from
  // below as lam -> 0 and there is no way to write 1 minus it in a double that
  // keeps the digits -- so its conditioning is added to the tolerance instead:
  // an absolute error of ~eps in Q is an error of eps/P in ln P. Small-lam
  // k = 2 is covered by the golden table, which does not have this problem.
  std::mt19937_64 rng(20260913);
  std::uniform_real_distribution<double> u(-8.0, 6.0);
  for (int i = 0; i < 4000; ++i) {
    const double lam = std::exp(u(rng));

    const double ref1 = (lam <= 0.6931471805599453)
                            ? std::log(-std::expm1(-lam))
                            : std::log1p(-std::exp(-lam));
    check_near(pto::peaks::log_poisson_sf(1, lam), ref1,
               poisson_tolerance(1, lam, ref1) + 8.0 * kEps * std::fabs(ref1),
               "k=1 closed form", __LINE__);

    const double ref2 = std::log1p(-std::exp(-lam) * (1.0 + lam));
    const double cond2 = 8.0 * kEps / std::exp(ref2);  // the reference's own limit
    check_near(pto::peaks::log_poisson_sf(2, lam), ref2,
               poisson_tolerance(2, lam, ref2) + cond2, "k=2 closed form", __LINE__);
  }
}

void test_sf_is_monotone() {
  // Two properties that hold for every Poisson, and that no approximation is
  // allowed to break: the tail shrinks as the threshold rises, and grows as
  // the background rises. A series that stops one term early breaks the first;
  // a branch seam that disagrees with itself breaks the second.
  for (double lam : {0.1, 1.0, 7.0, 100.0, 1e4, 1e6}) {
    double prev = 0.0;
    for (std::uint32_t k = 1; k <= 400; ++k) {
      const double v = pto::peaks::log_poisson_sf(k, lam);
      CHECK_MSG(v <= prev + 1e-12,
                "k=" + std::to_string(k) + " lam=" + num(lam) + ": " + num(v) +
                    " > " + num(prev));
      prev = v;
    }
  }
  for (std::uint32_t k : {1u, 2u, 17u, 511u, 512u, 513u, 5000u}) {
    double prev = -kInf;
    for (int i = -60; i <= 60; ++i) {
      const double lam = std::exp(static_cast<double>(i) * 0.25) * (k + 1.0);
      const double v = pto::peaks::log_poisson_sf(k, lam);
      CHECK_MSG(v >= prev - 1e-12,
                "k=" + std::to_string(k) + " lam=" + num(lam) + ": " + num(v) +
                    " < " + num(prev));
      prev = v;
    }
  }
}

void test_sf_branch_seam_is_continuous() {
  // The series and the continued fraction meet at lambda = k+1. They are two
  // different algorithms for one function, and the seam is exactly where a
  // wrong constant in either would show as a step -- and nowhere else.
  for (std::uint32_t k : {1u, 2u, 10u, 100u, 512u, 513u, 10000u}) {
    const double edge = static_cast<double>(k) + 1.0;
    const double below = pto::peaks::log_poisson_sf(k, std::nextafter(edge, 0.0));
    const double at = pto::peaks::log_poisson_sf(k, edge);
    const double above = pto::peaks::log_poisson_sf(k, std::nextafter(edge, kInf));
    // Bounded by the error model, not by a round number. At k = 10000 the
    // terms of `lead` reach 1.8e5, so two adjacent lambdas legitimately differ
    // in the eleventh digit; a wrong constant in either branch moves the
    // answer in the first or second, which this still catches.
    const double tol = 2.0 * poisson_tolerance(k, edge, at) + 1e-13;
    CHECK_NEAR(below, at, tol);
    CHECK_NEAR(at, above, tol);
  }
}

void test_sf_fails_closed_on_a_degenerate_lambda() {
  // A background of zero, a NaN from an empty window, an infinity from a
  // division that should not have happened: none of these is evidence of
  // enrichment. The repo's rule is that a filter fails CLOSED, and for a
  // p-value "closed" is p = 1 -- ln p = 0 -- never p = 0, which is what a
  // naive -lam + k*ln(lam) would produce for lambda -> 0 and would report
  // every unmeasured window as the most significant peak in the genome.
  for (std::uint32_t k : {0u, 1u, 2u, 512u, 513u, 100000u, 4294967295u}) {
    CHECK(pto::peaks::log_poisson_sf(k, 0.0) == 0.0);
    CHECK(pto::peaks::log_poisson_sf(k, -0.0) == 0.0);
    CHECK(pto::peaks::log_poisson_sf(k, -1.0) == 0.0);
    CHECK(pto::peaks::log_poisson_sf(k, -1e300) == 0.0);
    CHECK(pto::peaks::log_poisson_sf(k, kNaN) == 0.0);
    CHECK(pto::peaks::log_poisson_sf(k, kInf) == 0.0);
    CHECK(pto::peaks::log_poisson_sf(k, -kInf) == 0.0);
    CHECK(pto::peaks::neg_log10_poisson_sf(k, 0.0) == 0.0);
    CHECK(pto::peaks::neg_log10_poisson_sf(k, kNaN) == 0.0);
  }
}

void test_sf_is_always_finite_and_non_positive() {
  // A p-value is in [0, 1], so its logarithm is in [-inf, 0]. This sweep is
  // deliberately indiscriminate -- denormal lambdas, lambdas larger than any
  // pileup, counts past 2^31 -- because the guarantee is unconditional and the
  // inputs that break such a guarantee are never the ones a table lists.
  const double lams[] = {5e-324, 1e-300, 1e-30, 1e-6, 0.001, 1.0,  3.5,
                         100.0,  9999.0, 1e6,   1e12, 1e30,  1e100, 1e300};
  const std::uint32_t ks[] = {0u,   1u,     2u,      3u,       15u,
                              16u,  17u,    511u,    512u,     513u,
                              514u, 1000u,  65535u,  1000000u, 16777217u,
                              2147483647u,  2147483648u,       4294967295u};
  for (double lam : lams) {
    for (std::uint32_t k : ks) {
      const double v = pto::peaks::log_poisson_sf(k, lam);
      CHECK_MSG(std::isfinite(v),
                "k=" + std::to_string(k) + " lam=" + num(lam) + " -> " + num(v));
      CHECK_MSG(v <= 0.0,
                "k=" + std::to_string(k) + " lam=" + num(lam) + " -> " + num(v));
      const double q = pto::peaks::neg_log10_poisson_sf(k, lam);
      CHECK_MSG(std::isfinite(q) && q >= 0.0,
                "-log10 k=" + std::to_string(k) + " lam=" + num(lam) + " -> " + num(q));
    }
  }
}

void test_sf_extreme_counts_stay_in_double_range() {
  // k near 2^32 makes lnGamma(k) ~ 9.1e10 -- five orders of magnitude short of
  // overflow, but far enough that the ulp of the leading term is 1e-5. The
  // answer must still be a number, and it must still be the right one.
  const double v = pto::peaks::log_poisson_sf(4294967295u, 1e6);
  check_near(v, -31634289781.870898019,
             poisson_tolerance(4294967295u, 1e6, -31634289781.870898019),
             "k=2^32-1 lam=1e6", __LINE__);
  CHECK(std::isfinite(pto::peaks::neg_log10_poisson_sf(4294967295u, 1.0)));
}

// Torture 2026-09-10: the iteration cap.
//
// PeakCaller::clamp_count saturates a pileup at 2^32 - 1, so every k up to that
// reaches this model, and near lambda = k the series needs about
// sqrt(2 k ln 1e18) terms -- ~600,000 at the ceiling. With kMaxIterations at
// 100,000 every case below except the k = 1e8 control came back exactly p = 1:
// bases 4, 9 and 19 -log10 units above the default cutoff of 2, scored as
// nothing, in the scalar function and in every vector kernel.
//
// References: mpmath 1.3.0 at 40 digits,
//     -log10(1 - gammainc(k, lambda, inf, regularized=True)).
// Tolerances come from poisson_tolerance(), not from what the kernels produce.
void test_sf_converges_at_the_count_ceiling() {
  struct Golden {
    std::uint32_t k;
    double lambda;
    double neg_log10;
  };
  const Golden cases[] = {
      {4294967295u, 4294705151.0, 4.49947492632003},   // 4 sigma
      {4294967295u, 4294574079.0, 9.00634049139448},   // 6 sigma
      {4294967295u, 4294377471.0, 18.9490741971409},   // 9 sigma
      {4294967295u, 4294967295.0, 0.301028233191656},  // lambda = k, p ~ 1/2
      {1000000000u, 999873508.8, 4.49963053143886},    // 4 sigma at 1e9
      {100000000u, 99960000.0, 4.50025276466744},      // control: converged before
  };
  const double ln10 = std::log(10.0);
  std::vector<std::uint32_t> ks;
  std::vector<double> lams;
  std::vector<double> tols;
  for (const Golden& g : cases) {
    const double tol = poisson_tolerance(g.k, g.lambda, -g.neg_log10 * ln10) / ln10;
    const double got = pto::peaks::neg_log10_poisson_sf(g.k, g.lambda);
    CHECK_MSG(got > 0.0, "k=" + std::to_string(g.k) + " lam=" + num(g.lambda) +
                             " returned p = 1: the series did not converge");
    check_near(got, g.neg_log10, tol, "ceiling scalar", __LINE__);
    ks.push_back(g.k);
    lams.push_back(g.lambda);
    tols.push_back(tol);
  }
  std::vector<double> out(ks.size());
  pto::peaks::neg_log10_poisson_sf_batch(ks.data(), lams.data(), out.data(), ks.size());
  for (std::size_t i = 0; i < ks.size(); ++i) {
    check_near(out[i], cases[i].neg_log10, tols[i], "ceiling dispatched batch", __LINE__);
  }
}

void test_sf_denormal_lambda() {
  // lambda = 1e-320 is subnormal. P(X >= 1) = 1 - e^-lam ~ lam, so the answer
  // is ln(lambda) -- which the log kernel only reaches if it rescales
  // subnormals before splitting off the exponent.
  for (double lam : {1e-310, 1e-315, 1e-320, 5e-324}) {
    const double ref = std::log(-std::expm1(-lam));
    check_near(pto::peaks::log_poisson_sf(1, lam), ref, 1e-12 * std::fabs(ref),
               "denormal lambda", __LINE__);
  }
}

void test_neg_log10_is_the_scaled_negation() {
  std::mt19937_64 rng(20260914);
  std::uniform_int_distribution<std::uint32_t> kd(0, 5000);
  std::uniform_real_distribution<double> ld(0.01, 5000.0);
  for (int i = 0; i < 5000; ++i) {
    const std::uint32_t k = kd(rng);
    const double lam = ld(rng);
    const double ln = pto::peaks::log_poisson_sf(k, lam);
    const double q = pto::peaks::neg_log10_poisson_sf(k, lam);
    CHECK_REL(q, -ln / std::log(10.0), 1e-14);
  }
}

// poisson_pmf_upper_bound backs peaks/caller.hpp's skip bands: a base can be
// classified below the cutoff from this bound alone, without the tail sum
// neg_log10_poisson_sf needs, PROVIDED the bound is never smaller than the
// real answer -- checked here against the same golden-tested function these
// tests already trust, at both random points and the boundary (lambda == k)
// the bound's own comment claims is its minimum.
void test_pmf_upper_bound_never_understates_the_real_score() {
  std::mt19937_64 rng(20260916);
  std::uniform_int_distribution<std::uint32_t> kd(1, 100000);  // k=0 is not this bound's case
  std::uniform_real_distribution<double> ld(1e-6, 100000.0);
  for (int i = 0; i < 20000; ++i) {
    const std::uint32_t k = kd(rng);
    const double lam = ld(rng);
    const double exact = pto::peaks::neg_log10_poisson_sf(k, lam);
    const double bound = pto::peaks::poisson_pmf_upper_bound(k, lam);
    CHECK_MSG(bound >= exact - 1e-9,
              "k=" + std::to_string(k) + " lambda=" + std::to_string(lam) +
                  " bound=" + std::to_string(bound) + " exact=" + std::to_string(exact));
  }
  // The exact boundary the caller's skip-band construction bisects around.
  for (std::uint32_t k : {1u, 2u, 10u, 1000u, 100000u}) {
    const double exact = pto::peaks::neg_log10_poisson_sf(k, static_cast<double>(k));
    const double bound = pto::peaks::poisson_pmf_upper_bound(k, static_cast<double>(k));
    CHECK_MSG(bound >= exact - 1e-9,
              "k=" + std::to_string(k) + " (lambda=k) bound=" + std::to_string(bound) +
                  " exact=" + std::to_string(exact));
  }
}

// U(k, .)'s own claim: strictly convex in lambda, minimised exactly at
// lambda = k. Checked directly on the bound itself (not through the exact
// score, which need not share this shape) since that is the property the
// caller's bisection relies on to have exactly two roots, not zero or four.
void test_pmf_upper_bound_is_minimised_at_lambda_equals_k() {
  std::mt19937_64 rng(20260916);
  std::uniform_int_distribution<std::uint32_t> kd(1, 10000);
  std::uniform_real_distribution<double> factor_d(0.01, 100.0);
  for (int i = 0; i < 5000; ++i) {
    const std::uint32_t k = kd(rng);
    const double at_k = pto::peaks::poisson_pmf_upper_bound(k, static_cast<double>(k));
    const double factor = factor_d(rng);
    if (std::fabs(factor - 1.0) < 1e-6) continue;  // avoid comparing k against itself
    const double elsewhere =
        pto::peaks::poisson_pmf_upper_bound(k, static_cast<double>(k) * factor);
    CHECK_MSG(elsewhere >= at_k - 1e-9,
              "k=" + std::to_string(k) + " factor=" + std::to_string(factor) +
                  " at_k=" + std::to_string(at_k) + " elsewhere=" + std::to_string(elsewhere));
  }
}

void test_sf_is_deterministic() {
  // Same input, same answer, whatever ran in between. An iteration cap keyed on
  // a value left over from the previous call would show up here and nowhere
  // else in this file.
  for (int rep = 0; rep < 3; ++rep) {
    for (const auto& g : kSfGolden) {
      CHECK(pto::peaks::log_poisson_sf(g.k, g.lam) ==
            pto::peaks::log_poisson_sf(g.k, g.lam));
    }
  }
}

// ===========================================================================
// 3b. The finite lower sum, and the gate that decides when it may answer
//
// P(X >= k) = 1 - sum_{i<k} pmf(i). That sum is finite, so for small k it is
// cheaper than either infinite series and it needs no convergence test at all
// -- which is what lets the vector kernels run a fixed trip count with their
// lanes in lockstep. What it cannot do is reach the deep tail, because the
// answer is 1 minus a number that has gone to 1.
//
// So there is a gate, and a constant in it, and the whole point of these two
// cases is that the constant is MEASURED rather than argued for.
// ===========================================================================

// Recomputes the header's admissibility rule. Duplicated here on purpose: if
// the header widens its gate, this test must fail rather than quietly widen
// with it.
bool finite_path_admits(std::uint32_t k, double lam, double& q_out) {
  if (k == 0 || k > pto::peaks::detail::kFiniteMaxK) return false;
  if (!(lam > 0.0) || lam > pto::peaks::detail::kFiniteMaxLambda) return false;
  q_out = pto::peaks::detail::finite_lower_sum(k, lam);
  return 1.0 - q_out >= pto::peaks::detail::kFiniteMinTail;
}

void test_finite_path_gate_is_conservative() {
  // Walk the whole grid the fast path can be admitted on and compare it
  // against the exact path, scored against the SAME error model every other
  // case in this file uses. The measured worst case is 4.2% of the budget;
  // the quarter-budget bound below is where that stops being comfortable.
  //
  // Loosening kFiniteMinTail is what this guards. At 2^-9 the worst case is
  // 44% of budget and at 1e-4 it is 587% -- i.e. wrong -- so the constant is
  // not a round number someone picked, it is the last power of two with room
  // to spare.
  double worst = 0.0;
  std::uint32_t worst_k = 0;
  double worst_lam = 0.0;
  long long admitted = 0;
  for (std::uint32_t k = 1; k <= pto::peaks::detail::kFiniteMaxK; ++k) {
    for (int e = -700; e <= 40; ++e) {
      for (double mul : {1.0, 1.3, 1.7}) {
        const double lam = std::ldexp(mul, e);
        if (!std::isfinite(lam) || lam <= 0.0) continue;
        double q = 0.0;
        if (!finite_path_admits(k, lam, q)) continue;
        ++admitted;
        const double fast = pto::peaks::detail::finalise(pto::peaks::log1p_approx(-q));
        const double exact = pto::peaks::detail::sf_exact(k, lam);
        const double ratio = std::fabs(fast - exact) /
                             (poisson_tolerance(k, lam, exact) + 1e-300);
        if (ratio > worst) {
          worst = ratio;
          worst_k = k;
          worst_lam = lam;
        }
      }
    }
  }
  CHECK_MSG(admitted > 1000, "the sweep admitted only " + std::to_string(admitted) +
                                 " points; the gate is not being exercised");
  CHECK_MSG(worst < 0.25, "worst fast/exact disagreement is " + num(worst) +
                              " of the tolerance budget at k=" +
                              std::to_string(worst_k) + " lam=" + num(worst_lam));
  std::printf("  [finite gate: %lld points admitted, worst %.3g of budget]\n",
              admitted, worst);
}

void test_finite_path_carries_the_common_case() {
  // A fast path that has quietly stopped being taken is a performance
  // regression that no correctness test can see. On a background track -- the
  // realistic shape, where the pileup k is drawn AROUND the local lambda
  // rather than independently of it -- it must answer for the large majority.
  std::mt19937_64 rng(20260920);
  std::uniform_real_distribution<double> lu(0.5, 12.0);
  long long fast = 0;
  const long long n = 200000;
  for (long long i = 0; i < n; ++i) {
    const double lam = lu(rng);
    std::poisson_distribution<int> pd(lam);
    const std::uint32_t k = static_cast<std::uint32_t>(pd(rng));
    double q = 0.0;
    if (k != 0 && finite_path_admits(k, lam, q)) ++fast;
  }
  const double frac = 100.0 * static_cast<double>(fast) / static_cast<double>(n);
  CHECK_MSG(frac > 90.0, "finite path covers only " + num(frac) + "% of a background track");
  std::printf("  [finite path covers %.1f%% of a background track]\n", frac);
}

void test_finite_and_exact_paths_agree_on_the_golden_table() {
  // Every golden value, forced down the exact path, whatever log_poisson_sf
  // chose. Without this the goldens would silently stop covering the series
  // and continued fraction the moment the fast path took over.
  for (const auto& g : kSfGolden) {
    if (g.k == 0) continue;
    const double exact = pto::peaks::detail::sf_exact(g.k, g.lam);
    check_near(exact, g.ln_sf, poisson_tolerance(g.k, g.lam, g.ln_sf),
               "sf_exact golden", __LINE__);
  }
}

// ===========================================================================
// 4. Batch kernels and SIMD/scalar parity
// ===========================================================================

const IsaLevel kAllIsas[] = {IsaLevel::kScalar, IsaLevel::kNeon, IsaLevel::kAvx2,
                             IsaLevel::kAvx512};

void test_isa_dispatch_is_sane() {
  CHECK(pto::peaks::isa_compiled(IsaLevel::kScalar));
  CHECK(pto::peaks::isa_compiled(pto::peaks::isa_level()));
  CHECK(pto::peaks::isa_lanes(IsaLevel::kScalar) == 1);
  for (IsaLevel isa : kAllIsas) {
    CHECK(pto::peaks::isa_name(isa) != nullptr);
    CHECK(pto::peaks::isa_lanes(isa) >= 1);
  }
  std::printf("  [dispatch selects %s, %zu lanes]\n",
              pto::peaks::isa_name(pto::peaks::isa_level()),
              pto::peaks::isa_lanes(pto::peaks::isa_level()));
}

// A workload that reaches every branch in the kernel: both sides of the
// series/continued-fraction split, both sides of the log-factorial table seam,
// k = 0, counts past 2^31, and the degenerate lambdas that must fail closed.
void build_mixed_workload(std::vector<std::uint32_t>& ks, std::vector<double>& lams,
                          std::size_t n, std::uint64_t seed) {
  std::mt19937_64 rng(seed);
  std::uniform_int_distribution<int> shape(0, 9);
  std::uniform_real_distribution<double> u(0.0, 1.0);
  ks.clear();
  lams.clear();
  for (std::size_t i = 0; i < n; ++i) {
    std::uint32_t k = 0;
    double lam = 1.0;
    switch (shape(rng)) {
      case 0: k = 0; lam = u(rng) * 100.0 + 0.001; break;
      case 1: k = static_cast<std::uint32_t>(u(rng) * 20) + 1; lam = u(rng) * 5.0 + 1e-6; break;
      case 2: k = static_cast<std::uint32_t>(u(rng) * 600) + 1; lam = u(rng) * 600.0 + 1e-3; break;
      case 3: k = 512 + static_cast<std::uint32_t>(u(rng) * 5); lam = u(rng) * 1000.0 + 1.0; break;
      case 4: k = static_cast<std::uint32_t>(u(rng) * 100000) + 1; lam = u(rng) * 100000.0 + 1.0; break;
      case 5: k = 40; lam = 41.0 + (u(rng) - 0.5) * 1e-9; break;   // straddles the seam
      case 6: k = static_cast<std::uint32_t>(u(rng) * 4294967295.0); lam = 1e6; break;
      case 7: k = static_cast<std::uint32_t>(u(rng) * 50) + 1; lam = 0.0; break;      // guard
      case 8: k = static_cast<std::uint32_t>(u(rng) * 50) + 1; lam = kNaN; break;     // guard
      default: k = static_cast<std::uint32_t>(u(rng) * 50) + 1; lam = 1e-310; break;  // denormal
    }
    ks.push_back(k);
    lams.push_back(lam);
  }
}

void test_scalar_batch_is_exactly_the_scalar_function() {
  // Not "close to": identical. The scalar batch is DEFINED as the elementwise
  // scalar function, which is what makes it a usable reference for the vector
  // kernels -- a scalar batch that had quietly acquired its own arithmetic
  // would turn every parity failure below into an argument about tolerances.
  std::vector<std::uint32_t> ks;
  std::vector<double> lams;
  build_mixed_workload(ks, lams, 997, 20260915);
  std::vector<double> out(ks.size(), 12345.0);
  pto::peaks::log_poisson_sf_batch_isa(IsaLevel::kScalar, ks.data(), lams.data(),
                                       out.data(), ks.size());
  for (std::size_t i = 0; i < ks.size(); ++i) {
    const double want = pto::peaks::log_poisson_sf(ks[i], lams[i]);
    CHECK_MSG(out[i] == want, "i=" + std::to_string(i) + " k=" +
                                  std::to_string(ks[i]) + " lam=" + num(lams[i]) +
                                  ": " + num(out[i]) + " vs " + num(want));
  }
}

void test_every_compiled_isa_agrees_with_scalar() {
  std::vector<std::uint32_t> ks;
  std::vector<double> lams;
  build_mixed_workload(ks, lams, 4096, 20260916);

  std::vector<double> want(ks.size());
  pto::peaks::log_poisson_sf_batch_isa(IsaLevel::kScalar, ks.data(), lams.data(),
                                       want.data(), ks.size());

  for (IsaLevel isa : kAllIsas) {
    if (!pto::peaks::isa_compiled(isa)) continue;
    std::vector<double> got(ks.size(), 12345.0);
    pto::peaks::log_poisson_sf_batch_isa(isa, ks.data(), lams.data(), got.data(),
                                         ks.size());
    for (std::size_t i = 0; i < ks.size(); ++i) {
      const double tol = 2.0 * poisson_tolerance(ks[i], lams[i], want[i]);
      check_near(got[i], want[i], tol + 1e-300,
                 (std::string("isa=") + pto::peaks::isa_name(isa) + " parity").c_str(),
                 __LINE__);
    }
    // The degenerate lanes are the ones a vector kernel is most likely to get
    // wrong: a masked select that lets a NaN lambda through produces a NaN
    // p-value, and a NaN compares false against every threshold, which is a
    // fail-OPEN skip rather than a visible error.
    for (std::size_t i = 0; i < ks.size(); ++i) {
      if (!(lams[i] > 0.0) || !std::isfinite(lams[i])) {
        CHECK_MSG(got[i] == 0.0, std::string("isa=") + pto::peaks::isa_name(isa) +
                                     " degenerate lane " + std::to_string(i) +
                                     " -> " + num(got[i]));
      }
    }
  }
}

void test_batch_handles_every_length_and_unaligned_input() {
  // The tail. A kernel that processes whole vectors and forgets the remainder
  // leaves the last few positions of a chromosome at whatever was in the
  // output buffer -- here, a recognisable 12345.
  std::vector<std::uint32_t> ks;
  std::vector<double> lams;
  build_mixed_workload(ks, lams, 80, 20260917);

  for (std::size_t n = 0; n <= 40; ++n) {
    for (std::size_t off = 0; off < 4; ++off) {
      std::vector<double> got(n + 8, 12345.0);
      pto::peaks::log_poisson_sf_batch(ks.data() + off, lams.data() + off,
                                       got.data(), n);
      for (std::size_t i = 0; i < n; ++i) {
        const double want = pto::peaks::log_poisson_sf(ks[i + off], lams[i + off]);
        check_near(got[i], want, 2.0 * poisson_tolerance(ks[i + off], lams[i + off], want) + 1e-300,
                   "unaligned batch", __LINE__);
      }
      for (std::size_t i = n; i < got.size(); ++i) {
        CHECK_MSG(got[i] == 12345.0, "wrote past n at " + std::to_string(i));
      }
    }
  }
  // n == 0 must touch nothing, including when the pointers are null.
  pto::peaks::log_poisson_sf_batch(nullptr, nullptr, nullptr, 0);
}

void test_lgamma_batch_matches_scalar_on_every_isa() {
  std::vector<double> z;
  std::mt19937_64 rng(20260918);
  std::uniform_real_distribution<double> u(0.0, 1.0);
  for (int i = 0; i < 4096; ++i) {
    switch (i % 6) {
      case 0: z.push_back(u(rng) * 16.0 + 1e-6); break;
      case 1: z.push_back(u(rng) * 1000.0 + 16.0); break;
      case 2: z.push_back(u(rng) * 1e8 + 1.0); break;
      case 3: z.push_back(std::exp(u(rng) * 200.0)); break;
      case 4: z.push_back(16.0 + (u(rng) - 0.5) * 1e-9); break;  // straddles the seam
      default: z.push_back(static_cast<double>(i)); break;
    }
  }
  for (IsaLevel isa : kAllIsas) {
    if (!pto::peaks::isa_compiled(isa)) continue;
    std::vector<double> got(z.size(), 12345.0);
    pto::peaks::lgamma_batch_isa(isa, z.data(), got.data(), z.size());
    for (std::size_t i = 0; i < z.size(); ++i) {
      const double want = pto::peaks::lgamma_approx(z[i]);
      check_near(got[i], want, std::fabs(want) * 16.0 * kEps + 1e-13,
                 (std::string("isa=") + pto::peaks::isa_name(isa) + " lgamma parity").c_str(),
                 __LINE__);
    }
  }
  for (std::size_t n = 0; n <= 40; ++n) {
    std::vector<double> got(n + 8, 12345.0);
    pto::peaks::lgamma_batch(z.data() + 1, got.data(), n);
    for (std::size_t i = 0; i < n; ++i) {
      CHECK_REL(got[i], pto::peaks::lgamma_approx(z[i + 1]), 1e-13);
    }
    for (std::size_t i = n; i < got.size(); ++i) CHECK(got[i] == 12345.0);
  }
}

void test_neg_log10_batch_matches_scalar() {
  std::vector<std::uint32_t> ks;
  std::vector<double> lams;
  build_mixed_workload(ks, lams, 1024, 20260919);
  std::vector<double> got(ks.size(), 12345.0);
  pto::peaks::neg_log10_poisson_sf_batch(ks.data(), lams.data(), got.data(), ks.size());
  for (std::size_t i = 0; i < ks.size(); ++i) {
    const double want = pto::peaks::neg_log10_poisson_sf(ks[i], lams[i]);
    check_near(got[i], want,
               2.0 * poisson_tolerance(ks[i], lams[i], want) / std::log(10.0) + 1e-300,
               "neg_log10 batch", __LINE__);
  }
}

void test_batch_indexing_stays_inside_the_log_factorial_table() {
  // A vector gather indexed by the count itself reads out of bounds for any
  // k past the table, and reads a plausible double while doing it. This case
  // exists so the sanitizer build has something to catch: every entry is a
  // count on one side or the other of the boundary, and one is 2^32-1.
  std::vector<std::uint32_t> ks;
  std::vector<double> lams;
  for (std::uint32_t k = 500; k <= 530; ++k) {
    ks.push_back(k);
    lams.push_back(100.0);
  }
  for (std::uint32_t k : {65535u, 65536u, 1000000u, 2147483647u, 4294967295u}) {
    ks.push_back(k);
    lams.push_back(1e6);
  }
  std::vector<double> got(ks.size(), 0.0);
  for (IsaLevel isa : kAllIsas) {
    if (!pto::peaks::isa_compiled(isa)) continue;
    pto::peaks::log_poisson_sf_batch_isa(isa, ks.data(), lams.data(), got.data(),
                                         ks.size());
    for (std::size_t i = 0; i < ks.size(); ++i) {
      const double want = pto::peaks::log_poisson_sf(ks[i], lams[i]);
      check_near(got[i], want, 2.0 * poisson_tolerance(ks[i], lams[i], want) + 1e-300,
                 "table bounds", __LINE__);
    }
  }
}

// ===========================================================================
// 5. The hot-path rule, checked in the source rather than in a number
// ===========================================================================

void test_no_scalar_libm_calls_in_the_header() {
  // Every transcendental in this header is open-coded so that the vector
  // kernels have something to vectorise: there is no libm call that takes a
  // __m256d, and a scalar log() inside a per-position loop costs more than
  // everything around it. That property is a fact about the source, not about
  // any output value, so this is where it is checked -- the same argument
  // scrna_matrix's test_no_bare_float_accumulators makes.
  //
  // Classification (isfinite/isnan) and fabs are not on the list: they compile
  // to a test or a bit mask, not a call.
  const std::filesystem::path header =
      std::filesystem::path(PTO_PEAKS_SOURCE_DIR) / "include" / "peaks" / "poisson_model.hpp";
  std::ifstream in(header);
  if (!in) {
    // A guard that silently scans zero files reads as coverage. It is not.
    std::fprintf(stderr, "  FAIL cannot open %s for the libm scan\n",
                 header.string().c_str());
    ++g_failures;
    ++g_checks;
    return;
  }

  std::string src, line;
  std::size_t lineno = 0;
  std::vector<std::pair<std::size_t, std::string>> lines;
  while (std::getline(in, line)) {
    ++lineno;
    // Prose is allowed to name the functions it bans.
    const std::size_t comment = line.find("//");
    if (comment != std::string::npos) line.erase(comment);
    lines.emplace_back(lineno, line);
  }
  CHECK(lines.size() > 200);  // the scan ran over something

  const std::regex banned(
      R"((^|[^A-Za-z0-9_.>])(std::)?)"
      R"((log|log2|log10|log1p|logb|exp|exp2|expm1|pow|lgamma|tgamma|erf|erfc|)"
      R"(sin|cos|tan|atan|atan2|sinh|cosh|tanh|asinh|acosh|atanh|cbrt|hypot|)"
      R"(floor|ceil|round|rint|nearbyint|trunc|frexp|ldexp|scalbn|modf)f?)"
      R"(\s*\()");
  for (const auto& [no, text] : lines) {
    std::smatch m;
    if (std::regex_search(text, m, banned)) {
      report(false, "libm call in a hot path", __LINE__,
             header.filename().string() + ":" + std::to_string(no) + ": " + m.str());
    } else {
      ++g_checks;
    }
  }
}

// ===========================================================================

struct Case {
  const char* name;
  void (*fn)();
};

const Case kCases[] = {
    {"log kernel matches libm", test_log_kernel_matches_libm},
    {"exp kernel matches libm", test_exp_kernel_matches_libm},
    {"log1p kernel matches libm", test_log1p_kernel_matches_libm},
    {"log-factorial matches golden", test_log_factorial_matches_golden},
    {"log-factorial over and past the table", test_log_factorial_matches_libm_over_the_table_and_past_it},
    {"log-factorial table seam is continuous", test_log_factorial_table_seam_is_continuous},
    {"lgamma matches golden", test_lgamma_matches_golden},
    {"lgamma matches libm sweep", test_lgamma_matches_libm_sweep},
    {"lgamma guards its domain", test_lgamma_guards_its_domain},
    {"sf matches golden", test_sf_matches_golden},
    {"sf k=0 is exactly zero", test_sf_k_zero_is_exactly_zero},
    {"sf small-k closed forms", test_sf_small_k_closed_forms},
    {"sf is monotone", test_sf_is_monotone},
    {"sf branch seam is continuous", test_sf_branch_seam_is_continuous},
    {"sf fails closed on a degenerate lambda", test_sf_fails_closed_on_a_degenerate_lambda},
    {"sf is always finite and non-positive", test_sf_is_always_finite_and_non_positive},
    {"sf extreme counts stay in range", test_sf_extreme_counts_stay_in_double_range},
    {"sf converges at the count ceiling", test_sf_converges_at_the_count_ceiling},
    {"sf denormal lambda", test_sf_denormal_lambda},
    {"-log10 is the scaled negation", test_neg_log10_is_the_scaled_negation},
    {"pmf upper bound never understates the real score", test_pmf_upper_bound_never_understates_the_real_score},
    {"pmf upper bound is minimised at lambda = k", test_pmf_upper_bound_is_minimised_at_lambda_equals_k},
    {"sf is deterministic", test_sf_is_deterministic},
    {"finite path gate is conservative", test_finite_path_gate_is_conservative},
    {"finite path carries the common case", test_finite_path_carries_the_common_case},
    {"exact path still covers the goldens", test_finite_and_exact_paths_agree_on_the_golden_table},
    {"isa dispatch is sane", test_isa_dispatch_is_sane},
    {"scalar batch is the scalar function", test_scalar_batch_is_exactly_the_scalar_function},
    {"every compiled isa agrees with scalar", test_every_compiled_isa_agrees_with_scalar},
    {"batch handles every length and offset", test_batch_handles_every_length_and_unaligned_input},
    {"lgamma batch parity", test_lgamma_batch_matches_scalar_on_every_isa},
    {"-log10 batch matches scalar", test_neg_log10_batch_matches_scalar},
    {"batch stays inside the log-factorial table", test_batch_indexing_stays_inside_the_log_factorial_table},
    {"no scalar libm calls in the header", test_no_scalar_libm_calls_in_the_header},
};

}  // namespace

int main() {
  std::printf("== peaks/poisson_model ==\n");
  for (const auto& c : kCases) {
    const long long before = g_failures;
    c.fn();
    std::printf("  %s %s\n", g_failures == before ? "ok  " : "FAIL", c.name);
  }
  std::printf("%lld checks, %lld failure(s)\n", g_checks, g_failures);
  return g_failures == 0 ? 0 : 1;
}
