# Turns the contents of a directory into a single C++ translation unit of
# byte arrays, so the shipped binary carries its own dashboard and never needs
# a data directory, an installer step or a network fetch at runtime.
#
# Invoked as:
#   cmake -DASSET_DIR=<dir> -DOUTPUT_CPP=<file> -P cmake/embed_assets.cmake

if(NOT DEFINED ASSET_DIR OR NOT DEFINED OUTPUT_CPP)
  message(FATAL_ERROR "embed_assets.cmake requires -DASSET_DIR and -DOUTPUT_CPP")
endif()

file(GLOB_RECURSE ASSET_FILES RELATIVE "${ASSET_DIR}"
     "${ASSET_DIR}/*.html" "${ASSET_DIR}/*.css" "${ASSET_DIR}/*.js"
     "${ASSET_DIR}/*.svg" "${ASSET_DIR}/*.png" "${ASSET_DIR}/*.ico"
     "${ASSET_DIR}/*.woff2" "${ASSET_DIR}/*.json")

# Anything under web/src/ is frontend source, not a build output to embed.
list(FILTER ASSET_FILES EXCLUDE REGEX "^src/")

set(BODY "// Generated by cmake/embed_assets.cmake -- do not edit.\n")
string(APPEND BODY "#include \"embedded_assets.hpp\"\n\n")
string(APPEND BODY "namespace profiler::assets {\nnamespace {\n\n")

set(INDEX 0)
set(TABLE "")
foreach(REL IN LISTS ASSET_FILES)
  file(READ "${ASSET_DIR}/${REL}" HEX HEX)
  string(LENGTH "${HEX}" HEX_LEN)
  math(EXPR BYTE_LEN "${HEX_LEN} / 2")

  # "0a0b0c" -> "0x0a,0x0b,0x0c," wrapped at 16 bytes per line.
  string(REGEX REPLACE "(..)" "0x\\1," BYTES "${HEX}")
  string(REGEX REPLACE "((0x..,){16})" "\\1\n    " BYTES "${BYTES}")

  string(APPEND BODY "// ${REL} (${BYTE_LEN} bytes)\n")
  string(APPEND BODY "const unsigned char kBlob${INDEX}[] = {\n    ${BYTES}\n};\n\n")

  # Content type by extension; everything else is served as an octet stream.
  set(MIME "application/octet-stream")
  if(REL MATCHES "\\.html$")
    set(MIME "text/html; charset=utf-8")
  elseif(REL MATCHES "\\.css$")
    set(MIME "text/css; charset=utf-8")
  elseif(REL MATCHES "\\.js$")
    set(MIME "application/javascript; charset=utf-8")
  elseif(REL MATCHES "\\.svg$")
    set(MIME "image/svg+xml")
  elseif(REL MATCHES "\\.png$")
    set(MIME "image/png")
  elseif(REL MATCHES "\\.ico$")
    set(MIME "image/x-icon")
  elseif(REL MATCHES "\\.woff2$")
    set(MIME "font/woff2")
  elseif(REL MATCHES "\\.json$")
    set(MIME "application/json; charset=utf-8")
  endif()

  string(APPEND TABLE "    {\"/${REL}\", kBlob${INDEX}, ${BYTE_LEN}u, \"${MIME}\"},\n")
  math(EXPR INDEX "${INDEX} + 1")
endforeach()

if(INDEX EQUAL 0)
  message(FATAL_ERROR "no embeddable assets found in ${ASSET_DIR}")
endif()

string(APPEND BODY "}  // namespace\n\n")
string(APPEND BODY "const Asset kAssets[] = {\n${TABLE}};\n\n")
string(APPEND BODY "const unsigned long kAssetCount = ${INDEX}ul;\n\n")
string(APPEND BODY "}  // namespace profiler::assets\n")

# Only rewrite when the content actually changed, so an untouched frontend
# does not force a rebuild of everything downstream.
set(EXISTING "")
if(EXISTS "${OUTPUT_CPP}")
  file(READ "${OUTPUT_CPP}" EXISTING)
endif()
if(NOT EXISTING STREQUAL BODY)
  file(WRITE "${OUTPUT_CPP}" "${BODY}")
  message(STATUS "Embedded ${INDEX} asset(s) into ${OUTPUT_CPP}")
endif()
